#!/bin/bash
count=`ls -1 *.class 2>/dev/null | wc -l`
if [  $count != 0 ]
then
    rm *.class
fi

javac -cp ".:lib/*" Main.java
java -cp ".:lib/*" Main
date +%Y-%m-%d___%H:%M:%S >> times
rm bigramas.txt
echo 'Iteration was success'
