#!/bin/bash
count=`ls -1 *.class 2>/dev/null | wc -l`
if [  $count != 0 ]
then
    rm *.class
fi

javac -cp ".:lib/*" Main.java

echo "Numero de lineas":
read lines
date +%Y-%m-%d___%H:%M:%S >> times
java -cp ".:lib/*" Main $lines
